connect4/connect4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]

connect4/game/urls.py
from django.urls import path, re_path
from . import views

app_name = "game"
urlpatterns = [
    path('', views.index, name='index'),
    path('one-player/', views.onePlayer, name='one-player'),
    path('two-player/', views.twoPlayer, name='two-player'),
    re_path(r'^api/v1/move/(?P<pk>[0-2]{42})$', views.move_from_board)
]

connect4/game/models.py
from django.db import models

# Create your models here.
class Win(models.Model):
    winner = models.IntegerField(default=0)

connect4/game/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from rest_framework.decorators import api_view
import numpy as np
import math
import random
from .models import Win

def index(request):
  return render(request, 'game/index.html')

def twoPlayer(request):
  return render(request, 'game/two-players.html')

def onePlayer(request):
    
    context = {'player1': Win.objects.filter(winner=1).count(), 'player2': Win.objects.filter(winner=2).count()}
    return render(request, 'game/one-player.html', context)

ROW_COUNT = 6
COLUMN_COUNT = 7

EMPTY = 0
PLAYER_PIECE = 1
AI_PIECE = 2

WINDOW_LENGTH = 4

TERMINAL_NO_WIN = 0
TERMINAL_PLAYER_WIN = PLAYER_PIECE
TERMINAL_AI_WIN = AI_PIECE
NON_TERMINAL = 3

def is_valid_location(board, col):
  return board[ROW_COUNT-1][col] == 0

def get_valid_locations(board):
  valid_locations = []
  for col in range(COLUMN_COUNT):
    if is_valid_location(board, col):
      valid_locations.append(col)
  return valid_locations

def winning_move(board, piece):
  # Check horizontal locations for win
  for c in range(COLUMN_COUNT-3):
    for r in range(ROW_COUNT):
      if board[r][c] == piece and board[r][c+1] == piece and board[r][c+2] == piece and board[r][c+3] == piece:
        return True

  # Check vertical locations for win
  for c in range(COLUMN_COUNT):
    for r in range(ROW_COUNT-3):
      if board[r][c] == piece and board[r+1][c] == piece and board[r+2][c] == piece and board[r+3][c] == piece:
        return True

  # Check positively sloped diaganols
  for c in range(COLUMN_COUNT-3):
    for r in range(ROW_COUNT-3):
      if board[r][c] == piece and board[r+1][c+1] == piece and board[r+2][c+2] == piece and board[r+3][c+3] == piece:
        return True

  # Check negatively sloped diaganols
  for c in range(COLUMN_COUNT-3):
    for r in range(3, ROW_COUNT):
      if board[r][c] == piece and board[r-1][c+1] == piece and board[r-2][c+2] == piece and board[r-3][c+3] == piece:
        return True

def get_terminal_state(board):
  if winning_move(board, PLAYER_PIECE):
    return TERMINAL_PLAYER_WIN
  elif winning_move(board, AI_PIECE):
    return TERMINAL_AI_WIN
  elif len(get_valid_locations(board)) == 0:
    return TERMINAL_NO_WIN
  return NON_TERMINAL

def evaluate_window(window, piece):
  score = 0
  opp_piece = PLAYER_PIECE
  if piece == PLAYER_PIECE:
    opp_piece = AI_PIECE

  if window.count(piece) == 4:
    score += 100
  elif window.count(piece) == 3 and window.count(EMPTY) == 1:
    score += 5
  elif window.count(piece) == 2 and window.count(EMPTY) == 2:
    score += 2

  if window.count(opp_piece) == 3 and window.count(EMPTY) == 1:
    score -= 4

  return score

def score_position(board, piece):
  score = 0

  ## Score center column
  center_array = [int(i) for i in list(board[:, COLUMN_COUNT//2])]
  center_count = center_array.count(piece)
  score += center_count * 3

  ## Score Horizontal
  for r in range(ROW_COUNT):
    row_array = [int(i) for i in list(board[r,:])]
    for c in range(COLUMN_COUNT-3):
      window = row_array[c:c+WINDOW_LENGTH]
      score += evaluate_window(window, piece)

  ## Score Vertical
  for c in range(COLUMN_COUNT):
    col_array = [int(i) for i in list(board[:,c])]
    for r in range(ROW_COUNT-3):
      window = col_array[r:r+WINDOW_LENGTH]
      score += evaluate_window(window, piece)

  ## Score posiive sloped diagonal
  for r in range(ROW_COUNT-3):
    for c in range(COLUMN_COUNT-3):
      window = [board[r+i][c+i] for i in range(WINDOW_LENGTH)]
      score += evaluate_window(window, piece)

  for r in range(ROW_COUNT-3):
    for c in range(COLUMN_COUNT-3):
      window = [board[r+3-i][c+i] for i in range(WINDOW_LENGTH)]
      score += evaluate_window(window, piece)

  return score

def get_next_open_row(board, col):
  for r in range(ROW_COUNT):
    if board[r][col] == 0:
      return r

def drop_piece(board, row, col, piece):
  board[row][col] = piece

def minimax(board, depth, alpha, beta, maximizingPlayer):
  if depth == 0:
    return (None, score_position(board, AI_PIECE))
  terminal_state = get_terminal_state(board)
  if terminal_state == TERMINAL_AI_WIN:
    return (None, 100000000000000)
  if terminal_state == TERMINAL_PLAYER_WIN:
    return (None, -10000000000000)
  if terminal_state == TERMINAL_NO_WIN:
    return (None, 0)
  valid_locations = get_valid_locations(board)
  if maximizingPlayer:
    value = -math.inf
    column = random.choice(valid_locations)
    for col in valid_locations:
      row = get_next_open_row(board, col)
      b_copy = board.copy()
      drop_piece(b_copy, row, col, AI_PIECE)
      new_score = minimax(b_copy, depth-1, alpha, beta, False)[1]
      if new_score > value:
        value = new_score
        column = col
      alpha = max(alpha, value)
      if alpha >= beta:
        break
    return column, value

  else: # Minimizing player
    value = math.inf
    column = random.choice(valid_locations)
    for col in valid_locations:
      row = get_next_open_row(board, col)
      b_copy = board.copy()
      drop_piece(b_copy, row, col, PLAYER_PIECE)
      new_score = minimax(b_copy, depth-1, alpha, beta, True)[1]
      if new_score < value:
        value = new_score
        column = col
      beta = min(beta, value)
      if alpha >= beta:
        break
    return column, value

def search_for_move(b):
  col, minimax_score = minimax(b, 5, -math.inf, math.inf, True)
  return col

@api_view(['GET'])
def move_from_board(request, pk):
  if request.method == 'GET':
    if len(pk) != 42:
      return HttpResponseBadRequest('Invalid Board Configuration')
    board = np.flipud(np.asarray([int(x) for x in pk]).reshape((ROW_COUNT,COLUMN_COUNT))).copy()
    terminal_state = get_terminal_state(board)
    result = (False, 0, True, terminal_state)
    if terminal_state == NON_TERMINAL:
      col = search_for_move(board.copy())
      drop_piece(board, get_next_open_row(board, col), col, AI_PIECE)
      terminal_state = get_terminal_state(board)
      result = (True, col, True, terminal_state)
      if terminal_state == NON_TERMINAL:
        result = (True, col, False, 0)
    resp = dict(zip(('move_valid', 'move_col', 'is_finished', 'winner'), result))
    if resp["is_finished"]:
      winner = Win(winner=resp['winner'])
      winner.save()
      print(Win.objects.filter(winner=2).count(), resp['winner'])

    return JsonResponse(resp)

connect4/game/templates/game/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
	      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'game/style.css' %}" type="text/css" />
        <title>Welcome to Connect 4!</title>
    </head>

    <body>

      <div class="center-content">
        <img id="back-image" src="{% static 'game/images/background.jpg' %}" alt="Image of Connect 4" style="width:800px; margin-bottom: 24px;">
        <div class="center-content">
          <div class="menu-buttons">
            <ul>
              <li><a href="{% url 'game:one-player' %}">1 Player</a></li>
              <li><a href="{% url 'game:two-player' %}">2 Player</a></li>
            </ul>
          </div>
        </div>
      </div>

      
    
    </body>

</html>

connect4/game/templates/game/one-player.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'game/style.css' %}" type="text/css" />
        <title>template.html</title>
    </head>

    <body>

      <div class="center-content">
        <div id="game-board"></div>
      </div>

      <div class="bottom-menu">
        <ul>
          <li>Player1 Score: {{ player1 }}</li>
          <li><a href="{% url 'game:index' %}">Home</a></li>
          <li>AI Score: {{ player2 }}</li>
        </ul>
      </div>
    
    </body>


    <script>
      let gameBoard = document.querySelector("#game-board");
      for(let i=0; i < 7; i++) {  
          let column = document.createElement('div');
          column.setAttribute("style", `position: absolute; left: ${i * 150}px; top: 0px; height: 1050px; width: 150px;`);
          column.id = `column${i}`
          for(let j=0; j < 6; j++) {
            let square = document.createElement('div');
            column.appendChild(square);
            square.setAttribute("style", `position: absolute; left: ${0}px; top: ${j * 150}px; border-width: 2px; border-style: solid; width: 150px; height: 150px; background-color: transparent;`);
            let backdot = document.createElement('div');
            square.appendChild(backdot);
            backdot.setAttribute("style", 'position: absolute; left: 0px; top: 0px; border-radius: 50%; height: 140px; width: 140px; background-color: transparent; border-width: 2px; border-color: transparent; border-style: solid;');
            let frontdot = document.createElement('div');
            square.appendChild(frontdot);
            frontdot.setAttribute("style", 'position: absolute; left: 5px; top: 5px; border-radius: 50%; height: 140px; width: 140px; background-color: transparent; border-width: 2px; border-color: transparent; border-style: solid;');
          };
          column.onclick = function() {
            for(let k = 0; k <= column.children.length; k++) {
              if (k === column.children.length || column.children[k].children[1].style.backgroundColor != 'transparent') {
                if(k === 0) break;
                column.children[k - 1].children[0].style.backgroundColor = "darkred";
                column.children[k - 1].children[0].style.borderColor = "black";
                column.children[k - 1].children[1].style.backgroundColor = "red";
                column.children[k - 1].children[1].style.borderColor = "darkred";
                break;
              };
            };
            let winStr = "";
            let colCount = 7;
            let rowCount = 6;
            let empty = 0;
            let player1 = 1;
            let player2 = 2;
            for (let i = 0; i < rowCount; i++) {
              for (let j = 0; j < colCount; j++) {
                let currentColumn = document.querySelector(`#column${j}`)
                if (currentColumn.children[i].children[1].style.backgroundColor === "red") {
                  winStr += player1;
                } else if (currentColumn.children[i].children[1].style.backgroundColor === "blue") {
                  winStr += player2;
                } else {
                  winStr += empty;
                };
              }
            };

            new Promise((resolve, reject) => {
              $.getJSON({
                url: "/game/api/v1/move/" + winStr,
                success: function(data) {
                  resolve(data)
                },
              });
            }).then((data) => {
              if (data.move_valid) {
                let moveCol = document.querySelector(`#column${data.move_col}`);
                for(let i = 0; i < rowCount; i++) {
                  if(moveCol.children[rowCount - 1 - i].children[1].style.backgroundColor === "transparent") {
                    moveCol.children[rowCount - 1 - i].children[0].style.backgroundColor = "darkblue";
                    moveCol.children[rowCount - 1 - i].children[0].style.borderColor = "black";
                    moveCol.children[rowCount - 1 - i].children[1].style.backgroundColor = "blue";
                    moveCol.children[rowCount - 1 - i].children[1].style.borderColor = "darkblue";
                    break;
                  }
                }
              }
              if (data.is_finished) {
                if(data.winner == empty) {
                  alertVal = confirm(`The game is a draw`);
                } else {
                  alertVal = confirm(`Player ${data.winner} won!`);
                }
                location.reload();
              }
            });
          };
          gameBoard.appendChild(column);
        };
    </script>
</html>

connect4/game/templates/game/two-players.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <link rel="stylesheet" href="{% static 'game/style.css' %}" type="text/css" />
        <title>template.html</title>
    </head>

    <body>

      <div class="center-content">
        <div id="game-board"></div>
      </div>

      
      <div class="bottom-menu-1">
        <ul>
          <li><a href="{% url 'game:index' %}">Home</a></li>
        </ul>
      </div>
    
    </body>


    <script>
      let gameBoard = document.querySelector("#game-board");
      var whoseTurn = true;
      for(let i=0; i < 7; i++) {  
          let column = document.createElement('div');
          column.setAttribute("style", `position: absolute; left: ${i * 150}px; top: 0px; height: 1050px; width: 150px;`);
          column.id = `column${i}`
          for(let j=0; j < 6; j++) {
            let square = document.createElement('div');
            column.appendChild(square);
            square.setAttribute("style", `position: absolute; left: ${0}px; top: ${j * 150}px; border-width: 2px; border-style: solid; width: 150px; height: 150px; background-color: transparent;`);
            let backdot = document.createElement('div');
            square.appendChild(backdot);
            backdot.setAttribute("style", 'position: absolute; left: 0px; top: 0px; border-radius: 50%; height: 140px; width: 140px; background-color: transparent; border-width: 2px; border-color: transparent; border-style: solid;');
            let frontdot = document.createElement('div');
            square.appendChild(frontdot);
            frontdot.setAttribute("style", 'position: absolute; left: 5px; top: 5px; border-radius: 50%; height: 140px; width: 140px; background-color: transparent; border-width: 2px; border-color: transparent; border-style: solid;');
          };
          column.onclick = function() {
            for(let k = 0; k < column.children.length; k++) {
              if (column.children[k].children[0].style.backgroundColor != 'transparent') {
                if (k === 0) {
                  break;
                } else {
                  if (whoseTurn) {
                    column.children[k - 1].children[0].style.backgroundColor = "darkred";
                    column.children[k - 1].children[0].style.borderColor = "black";
                    column.children[k - 1].children[1].style.backgroundColor = "red";
                    column.children[k - 1].children[1].style.borderColor = "darkred";
                    whoseTurn = false;
                  } else {
                    column.children[k - 1].children[0].style.backgroundColor = "darkblue";
                    column.children[k - 1].children[0].style.borderColor = "black";
                    column.children[k - 1].children[1].style.backgroundColor = "blue";
                    column.children[k - 1].children[1].style.borderColor = "darkblue";
                    whoseTurn = true;
                  }
                  break;
                };
              };
              if (k === column.children.length - 1) {
                  if (whoseTurn) {
                    column.children[k].children[0].style.backgroundColor = "darkred";
                    column.children[k].children[0].style.borderColor = "black";
                    column.children[k].children[1].style.backgroundColor = "red";
                    column.children[k].children[1].style.borderColor = "darkred";
                    whoseTurn = false;
                  } else {
                    column.children[k].children[0].style.backgroundColor = "darkblue";
                    column.children[k].children[0].style.borderColor = "black";
                    column.children[k].children[1].style.backgroundColor = "blue";
                    column.children[k].children[1].style.borderColor = "darkblue";
                    whoseTurn = true;
                  };
              };
            };
          };
          gameBoard.appendChild(column);
          

          

        };
        gameBoard.onclick = function () {
          let winArray = [];
          let colCount = 7;
          let rowCount = 6;
          let empty = 0;
          let player1 = 1;
          let player2 = 2;
          for (let i = 0; i < colCount; i++) {
            winArray.push([]);
            let currentColumn = document.querySelector(`#column${i}`)
            for (let j = 0; j < rowCount; j++) {
              if (currentColumn.children[j].children[1].style.backgroundColor === "red") {
                winArray[i].push(player1);
              } else if (currentColumn.children[j].children[1].style.backgroundColor === "blue") {
                winArray[i].push(player2);
              } else {
                winArray[i].push(empty);
              };
            }
          };

          let alertVal = false;
          //Check Vertical
          for (let i = 0; i < colCount; i++) {
            for (let j = 0; j < rowCount - 3; j ++) {
              if (winArray[i][j] !== 0) {
                if (winArray[i][j] === winArray[i][j + 1] && winArray[i][j] === winArray[i][j + 2] && winArray[i][j] === winArray[i][j + 3] ) {
                  alertVal = confirm(`Player ${winArray[i][j]} won!`);
                };  
              };
            };
          };
          //Check Horizontal
          for (let i = 0; i < colCount - 3; i++) {
            for (let j = 0; j < rowCount; j ++) {
              if (winArray[i][j] !== 0) {
                if (winArray[i][j] === winArray[i + 1][j] && winArray[i][j] === winArray[i + 2][j] && winArray[i][j] === winArray[i + 3][j] ) {
                  alertVal = confirm(`Player ${winArray[i][j]} won!`);
                };  
              };
            };
          };
          //Check Diagonal Up
          for (let i = 0; i < colCount - 3; i++) {
            for (let j = 3; j < rowCount; j ++) {
              if (winArray[i][j] !== 0) {
                if (winArray[i][j] === winArray[i + 1][j - 1] && winArray[i][j] === winArray[i + 2][j - 2] && winArray[i][j] === winArray[i + 3][j - 3] ) {
                  alertVal = confirm(`Player ${winArray[i][j]} won!`);
                };  
              };
            };
          };

          //Check Diagonal Down
          for (let i = 0; i < colCount - 3; i++) {
            for (let j = 0; j < rowCount - 3; j ++) {
              if (winArray[i][j] !== 0) {
                if (winArray[i][j] === winArray[i + 1][j + 1] && winArray[i][j] === winArray[i + 2][j + 2] && winArray[i][j] === winArray[i + 3][j + 3] ) {
                  alertVal = confirm(`Player ${winArray[i][j]} won!`);
                };  
              };
            };
          };
          if (alertVal) {
            //Add some sort of post value through django
            window.location.reload();
          };
        };
        
        
    </script>
</html>